pipeline:
  name: remote_pipeline_1
  identifier: remote_pipeline_1
  projectIdentifier: Brijesh
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cs
        identifier: cs
        description: desc
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: gtrgfhjk
                  identifier: gtrgfhjk
                  template:
                    templateRef: http_remote_temp
                    versionLabel: "1.0"
                    templateInputs:
                      type: Http
                      spec:
                        method: <+input>.allowedValues(GET,POST)
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo Hi
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
