pipeline:
  name: remote_test_2
  identifier: remote_test_2
  projectIdentifier: Brijesh_Test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: DMON TF
        identifier: dmon_tf
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: HarnessApproval
                  name: Approval
                  identifier: Approval
                  spec:
                    approvalMessage: Please review the Plan step.
                    includePipelineExecutionHistory: true
                    approvers:
                      userGroups:
                        - account.CoreEngEngineer
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1h
        variables:
          - name: accountName
            type: String
            value: dmon
  variables:
    - name: branch
      type: String
      value: <+input>.default(master)
    - name: gitTag
      type: String
      value: <+input>
    - name: gitSHA
      type: String
      value: <+input>
    - name: changeRequest
      type: String
      value: <+input>.regex((?:\b(?:CHG|INC)\d{8}\b)?)
