pipeline:
  name: remote_pipeline_1
  identifier: remote_pipeline_1
  projectIdentifier: Brijesh
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: abc
        identifier: abc
        tags: {}
        template:
          templateRef: remote_stage
          versionLabel: "1.0"
