pipeline:
  name: remote_1
  identifier: remote_1
  projectIdentifier: Brijesh
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubdemotepo
        build: <+input>
  stages:
    - stage:
        name: ci
        identifier: ci
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: MacOS
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo HI
