pipeline:
  name: remote_test_2
  identifier: remote_test_2
  projectIdentifier: Brijesh_Test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: DMON TF
        identifier: dmon_tf
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: HarnessApproval
                  name: Approval
                  identifier: Approval
                  spec:
                    approvalMessage: Please review the Plan step.
                    includePipelineExecutionHistory: true
                    approvers:
                      userGroups:
                        - account.CoreEngEngineer
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1h
        variables:
          - name: accountName
            type: String
            value: dmon
  variables:
    - name: test
      type: String
      description: test
      value: <+input>
  allowStageExecutions: true
  timeout: 3h
