pipeline:
  name: remote_1
  identifier: remote_1
  projectIdentifier: Brijesh
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: p1
        identifier: p1
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: remote_child
          project: Brijesh
