version: 1
name: SimplifiedYamlPipeline
stages:
  - type: Custom
    strategy:
      matrix:
        a: ["a","b","c"]
        b: ["a","b","c"]
        maxConcurrency: 4
    spec:
      steps:
        - type: Http
          strategy:
            matrix:
              a: ["a","b", "c"]
              maxConcurrency: 3
          spec:
            method: GET
            url: http://www.google.com
        - type: Http
          strategy:
            matrix:
              a: ["a","b", "c"]
              maxConcurrency: 3
          spec:
            method: GET
            url: http://www.google.com
