pipeline:
  name: remote_1
  identifier: remote_1
  projectIdentifier: Brijesh
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: pip-stage
        identifier: pipstage
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: remotechild
          project: Brijesh
          inputSetReferences:
            - inputSet_2
    - stage:
        name: cs2
        identifier: cs2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: <+input>
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
