pipeline:
  name: remote_1
  identifier: remote_1
  projectIdentifier: Brijesh
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: pip-stage
        identifier: pipstage
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: remotechild
          project: Brijesh
