environment:
  name: remote_environment
  identifier: remote_environment
  tags: {}
  type: PreProduction
  orgIdentifier: default
  projectIdentifier: Brijesh
  variables:
    - name: var1
      type: String
      value: <+input>
      description: ""
      required: false
