pipeline:
  name: remote_pip
  identifier: remote_pip
  projectIdentifier: Brijesh
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cs
        identifier: cs
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo HI
                          echo "Non default"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - parallel:
        - stage:
            name: abcds
            identifier: abcds
            tags: {}
            template:
              templateRef: remote_stage
              versionLabel: "1.0"
        - stage:
            name: cssss
            identifier: cssss
            description: ""
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: ShellScript_1
                      identifier: ShellScript_1
                      spec:
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            script: exit 1
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
            tags: {}
  allowStageExecutions: true
