apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
  labels:
    #app: {{ne .Values.label "somestring"}}
    app: {{ .Values.label }}
spec:
  replicas: {{.Values.replica}}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:someinvalidtag
        ports:
        - containerPort: 80
